"""
A module for obtaining repo readme and language data from the github API.
Before using this module, read through it, and follow the instructions marked
TODO.
After doing so, run it like this:
    python acquire.py
To create the `data.json` file that contains the data.
"""
import os
import json
from typing import Dict, List, Optional, Union, cast
import requests

from env import github_token, github_username

# TODO: Make a github personal access token.
#     1. Go here and generate a personal access token https://github.com/settings/tokens
#        You do _not_ need select any scopes, i.e. leave all the checkboxes unchecked
#     2. Save it in your env.py file under the variable `github_token`
# TODO: Add your github username to your env.py file under the variable `github_username`
# TODO: Add more repositories to the `REPOS` list below.

REPOS = ['fabacab/awesome-cybersecurity-blueteam',
 'zer0yu/CyberSecurityRSS',
 'gerryguy311/Free_CyberSecurity_Professional_Development_Resources',
 'harisqazi1/Cybersecurity',
 'shramos/Awesome-Cybersecurity-Datasets',
 'DerekBabb/CyberSecurity',
 'paralax/awesome-cybersecurity-internships',
 'PacktPublishing/Machine-Learning-for-Cybersecurity-Cookbook',
 'llSourcell/Build-a-Cybersecurity-Startup',
 'Annsec/awesome-cybersecurity',
 'Sourabh-HackerEarth/CyberSecurity-Resource',
 'cybersecuritybase/cybersecuritybase.github.io',
 'noraj/rawsec-cybersecurity-inventory',
 'Ebiquity/Unified-Cybersecurity-Ontology',
 'roshanlam/ML_CyberSecurity',
 'scusec/Data-Mining-for-Cybersecurity',
 'guidesmiths/cybersecurity-handbook',
 'alex-bellon/cybersecurity-resources',
 'PacktPublishing/Hands-On-Artificial-Intelligence-for-Cybersecurity',
 'soprasteria/cybersecurity-dfm',
 'gfek/Real-CyberSecurity-Datasets',
 'soprasteria/cybersecurity-miw',
 'vmayoral/basic_robot_cybersecurity',
 'sophos-cybersecurity/solarwinds-threathunt',
 'andrewaeva/machine-learning-in-cybersecurity',
 'shramos/practical-ml-for-cybersecurity',
 'dmalan/cybersecurity',
 'emadshanab/Basic-knowledge-requirements-for-cybersecurity-and-hacking',
 'sdrttnclskn/ismek-cybersecurity1-lessons',
 'matrices-cloud/Awesome-ML-Cybersecurity',
 'scwuaptx/Global-Cybersecurity-Camp-2018',
 'guardsight/gsvsoc_cybersecurity-incident-response-plan',
 'viczong/cybersecurity_threat_severity_analysis',
 'GrandGarcon/Complete_Cybersecurity_Path',
 'emmanueltsukerman/Cybersecurity-Data-Science-on-Udemy',
 'HoloLen/CyberSecurity_Knowledge_graph',
 'CyberAndi/CyberSecurity-Box',
 'carriegardner428/cybersecurity_datascience',
 'binexisHATT/CyberSecurity',
 'sophos-cybersecurity/sophos-central-api-connector',
 'juliandariomirandacalle/DataScience_Cybersecurity',
 'HACK-BLOSSOM/DIY-Cybersecurity-For-Domestic-Violence',
 'rezaduty/cybersecurity-career-path',
 'Screetsec/Cybersecurity-Indonesia',
 'fractional-ciso/NIST-Cybersecurity-Documents',
 'anthares101/my_cybersecurity_notes',
 'abhisek3122/learn-cybersecurity',
 'Logo252/Machine-learning-for-cybersecurity',
 'achernikova/cybersecurity_evasion',
 'CCC-NLIP/DataSciForCybersecurity',
 'PacktPublishing/Cybersecurity-Attacks-Red-Team-Strategies',
 'usnistgov/IoT-Device-Cybersecurity-Requirement-Catalogs',
 'momopranto/BTHS-Cybersecurity-Club',
 'nansunsun/Cybersecurity-incident-prediction-and-discovery-data',
 'cit-pisa/CyberSecurity2020',
 'ForbiddenProgrammer/awesome-cybersecurity-news',
 'Scotoma8/CyberSecurity',
 'alphalegionwarrior/cybersecurity',
 'vinayakumarr/Cybersecurity-Lab-at-CEN',
 'NU-Cybersecurity/Toolset-Resource',
 'stelemate/BERT-for-Cybersecurity-NER',
 'ZE0TRON/CyberSecurityExamplesPython',
 'eastmountyxz/CyberSecurityBox',
 'CCrashZer0/CyberSecurityResources',
 'ForJournalism/fj-cybersecurity-and-online-privacy',
 'hanhanwu/Hanhan_CyberSecurity_DataScience',
 'eclipse/capella-cybersecurity',
 'ICT4SD/CyberSecurity_Strategies',
 'tianjingyu1/cyberSecurity',
 'Madhakee01/IBM_Cybersecurity_Analyst_Professional_Certificate',
 'UtkarshPathrabe/Cybersecurity-Specialization-University-Of-Maryland-Coursera',
 'vinnyfiore/CybersecurityThesaurus',
 'CristiVlad25/ml-cybersecurity',
 'CASES-LU/Fit4Cybersecurity',
 'Mostafayahia-hunter/Intro_to_cybersecurity',
 'ukk1/cybersecuritybase-project',
 'tertiarycourses/CyberSecurity',
 'yadav97/cyberSecurity',
 'tsnsoft/Cybersecurity-devices',
 'tsnsoft/Cybersecurity-gadgets',
 'extwiii/Cybersecurity-University.of.Maryland',
 'rrgoya/cybersecurity-capstone-project',
 'ulookme/CyberSecurity-Data-Science',
 'MrM8BRH/CyberSecurity_Conferences',
 'HaoScottSun/UN-Cybersecurity-Fordham-Core-Team',
 'ukk1/cybersecuritybase-CtF',
 'MichaelTanji/Cybersecurity-Pathfinders',
 'monksudo/CyberSecurityCollections',
 'Kothmun/Cybersecurity_Resources',
 'Dipeshtwis/cybersecurity_engine',
 'larryboettger/Cybersecurity-Mindmaps',
 'bhume/thai-cybersecurity-ecosystem-map',
 'edoardottt/MSc-CyberSecurity-Sapienza',
 'CyberSecurityUP/CyberSecurityUP',
 'herrfeder/AI_Cybersecurity_IDS_PoC',
 'dple/awesome-deep-learning-paper-for-cybersecurity',
 'glglgithub/CyberSecurity-A-Study-with-KDD99-Dataset',
 'sophos-cybersecurity/Incident-Response',
 'XenonIO/cybersecurity',
 'BetaZeon/CyberSecurity_Resources',
 'ResearchTriangleAnalysts/CyberSecurity',
 'LuD1161/CyberSecurity-IIITA',
 'wikibook/cybersecurity-with-blockchain',
 'iharnoor/CyberSecurityTemplate',
 'steventfisher/Cybersecurity-News-Crawler',
 'ricco386/CYBER501x-Cybersecurity-Fundamentals',
 'longxiaozhang/cybersecurity',
 'chanie01234/Cybersecurity',
 'Sharpforce/cybersecurity',
 'codepath/cybersecurity',
 '0x000N3X4N/cybersecurity',
 'nansunsun/CWE-Knowledge-Graph-Based-Twitter-Data-Analysis-for-Cybersecurity',
 'daylamtayari/Cybersecurity-Tools',
 'laziestcoder/CyberSecurityCourse',
 'Michieldoesburg/economics_of_cybersecurity',
 'soprasteria/cybersecurity-virtualize-windows-host',
 'KaranVani/CyberSecurityWebsite',
 'cyberdefendersprogram/python4cybersecurity',
 'CyberSecurityTechnology/CyberSecurityTechnology.github.io',
 'PacktPublishing/PowerShell-Automation-and-Scripting-for-CyberSecurity',
 'sophos-cybersecurity/credsleuth',
 'CU-Cybersecurity-Club/stock-trator',
 'lbnl-cybersecurity/LBNL_Physics_Based_IDS',
 'vladislavglad/Cybersecurity-Game-Project',
 'tomasreimers/Cybersecurity-wiki-tables',
 'IBMStreams/streamsx.cybersecurity.starterApps',
 'api-evangelist/cybersecurity',
 'ericholguin/CyberSecurityApp',
 'gnebbia/IBM_cybersecurity_notes',
 'SofianeHamlaoui/CyberSecurityCare',
 'HACK-BLOSSOM/DIY-Cybersecurity-For-Domestic-Violence-ES',
 'ckane/revolutionuc-cybersecurity',
 'santosomar/cybersecurity_fundamentals',
 'foolboy365/cybersecurity_knowledge',
 'TheCodingLama/CDAC-Workshop-CyberSecurity',
 'vishakha-b18/Cybersecurity-Threat-Prediction',
 'lbnl-cybersecurity/lbnl-cybersecurity.github.io',
 'imsiddhant/Palo-Alto-Networks-Cybersecurity-Specialization',
 'HarshOza36/Project_X-CyberSecurityInitiative',
 'jinsonvarghese/Cybersecurity',
 'HarshaDokula/CyberSecurity',
 'serdarhaliloglu/CyberSecurity',
 'reevesba/cybersecurity',
 'Heavy-Vehicle-Networking-At-U-Tulsa/CybersecurityForHVDERs',
 'csw-acm/cybersecurity',
 'BaliDataMan/cybersecurityproject',
 'MobileGuru1013/cybersecurity-miw',
 'GambuzX/Cybersecurity_Practice',
 'AlaaZorkane/cybersecurity-sessions',
 'ahhh/Cybersecurity-Tradecraft',
 'womenwhocodedc/cybersecurity-community',
 'j-chat/cybersecurity_training',
 'abhinavkk/CyberSecurity-Game',
 'marcobrador/coursera-cybersecurity-capstone-project',
 'Zwerd/CyberSecurityResearcherLearning',
 'gabrielluiz123/CyberSecuritySystem',
 'DefenseTeam/CyberSecurityAritcles',
 'shreyagopal/AI-Cybersecurity-DSCI-6672',
 'Ross015/CyberSecurityTools',
 'raisakarasik/lanl-auth-cybersecurity',
 'EricaSueWatkins/CyberSecurityBootcamp',
 'Chad-Ballay/Cybersecurity-work-class',
 'CyberICS/News-RSS-ICS-Cybersecurity',
 'deeprajCSE1729/CyberSecurity-Networking-Tips',
 'xaviablaza/cpsc370-01-cybersecurity',
 'sdobbs88/CyberSecurityEncryptionProject',
 'DavidLapadula/Python-automate-cybersecurity',
 'lorenzodemiri/AI-CyberSecurity',
 'pasks87/cybersecurity_automotive_can',
 'wes-petrimoulx/Cybersecurity-Malware-Analysis-Dashboard',
 'Madhakee01/Mosse-Cybersecurity-Internship',
 'ljl123/MachineLearning-Cybersecurity',
 'cloudstitch/the-cybersecurity-factory',
 'mazenhk/CyberSecurity_Data_Analysis',
 'dev-arda/CyberSecurity-Sources',
 'prathameshSatya/Java-Summer-Project---CyberSecurity',
 'PacktPublishing/Incident-Response-for-Cybersecurity-Professionals',
 'Ananya-0306/CyberSecurity_Certification_for_Free',
 'JonQuxBurton/CyberSecurityBasewithF-Secure',
 'TheMMcOfficial/start-in-IT-or-in-cybersecurity',
 'jrmmba8314/VMs-For-PAHS-Cybersecurity-and-Computer-Forensics-Class',
 'Cybersecurity-Programming-Team-4/Xerxes',
 'lbnl-cybersecurity/tstat-dtn-analysis',
 'coict-cybersecurity-community/Unix-Linux-collections',
 'spartixgit/cybersecurityquiz',
 'cybersecuritycourse/cybersecurity-rails',
 'deveyNull/Getting-into-InfoSec-and-Cybersecurity',
 'AndyYSWoo/CS269I-Cybersecurity',
 'grant100/cybersecurity-struts2',
 'UniteIdeas/CyberSecurityNLP',
 'iamsabhoho/cybersecurity',
 'alphagov/cybersecuritytools',
 'PepziC0les/Cybersecurity-CloudFormation',
 'ahmadi7/Python-For-Cybersecurity',
 'CyberBits/CyberSecurityWithML',
 'rtaormina/EWRI2018_CyberSecurityWorkshop',
 'PPCC-CareerStart-CyberSecurity/Robin-Pi',
 'EPHS-CyberSecurity-2020-Hour1/CipherProject',
 'lbnl-cybersecurity/ddos-detection',
 'Alpha-Cybersecurity/GeoAndroid',
 'ReshmaKotnur7330/cybersecurity7330',
 'iivorait/cybersecurityproject1',
 'KeepItOnTheDownload/CybersecurityGuides',
 'Irega97/CybersecurityServer',
 'SheyMouse/CybersecurityResources',
 'Lucy-SD-Developer/CyberSecurity',
 'walterkilar/Cybersecurity',
 'Jasmeet-1998/CyberSecurity',
 'avifeder/CyberSecurity',
 'Pranavjain23/CyberSecurity',
 'mar2nyuedu/cybersecurity',
 'KausikN/CyberSecurity',
 'roger8849/cybersecurity',
 'SaadDamine/Cybersecurity',
 'Geekpub/Cybersecurity',
 'Ohara124c41/Cybersecurity',
 'andreymyssak/Cybersecurity',
 'DeathWH/CyberSecurity',
 'apoorvab93/cybersecurity',
 'GIGwerk/Cybersecurity',
 'HDuCoing/CyberSecurity',
 'Ansh063/cybersecurity',
 'ahoopes16/cybersecurity',
 'RafatKhandaker/CyberSecurity',
 'kundanv/CyberSecurity',
 'pectoraux/Cybersecurity',
 'FinchforRoot/Cybersecurity',
 'vittalsiddaiah/CyberSecurity',
 'ancutamaria/CyberSecurity',
 'Ananya-0306/Cybersecurity',
 'jacobtb64/cybersecurity',
 'v-research/cybersecurity',
 'Njack-IITP/Cybersecurity',
 'cybersecurity4/cybersecurity4.github.io',
 'ccataldo345/CyberSecurity',
 'Brifurlong/CyberSecurity',
 'hadhehog/Cybersecurity',
 'hyzhou-student/CybersecurityProjectEmailServer',
 'tigerjpg/cybersecurity',
 'rhedshi/cybersecurity',
 'elsaVelazquez/cybersecurity',
 'HraklisTs/Cybersecurity',
 'AlessandroCanel/Cybersecurity',
 'papidalo/cybersecurity',
 'AdamPanag/CyberSecurity',
 'xbufu/CyberSecurity',
 'virus62/cybersecurity',
 'quadrature-hash/CybersecurityChallenge2020',
 'rakeshelamaran98/CyberSecurity',
 'Philser/cybersecurity',
 'ruffner/cybersecurity',
 'entroy0421/cybersecurity',
 'iwazirijr/IT727Class-CybersecurityRiskMgt',
 'bahraminekoo/cybersecuritytech',
 'franramos97/Cybersecurity_Master',
 'SandheepSridar/Cybersecurity-Assessment',
 'ianwolf99/Cybersecurity-Website',
 'ZBerritt/cybersecurity-website',
 'LiorBenAri/Cybersecurity-Simulation',
 'HannahReinbolt/cybersecurity-projects',
 'UMBC-ACCL/cybersecurity_embeddings',
 'Genesis-2020/Cybersecurity_Project',
 'jameshenderson12/cepeh-cybersecurity',
 'iricartb/university-cybersecurity',
 'Strong7091/Cybersecurity_Script',
 'Gbigley01/DU-Cybersecurity',
 'aomar6/UMN_Cybersecurity',
 'NoSoyTuMadre/Cybersecurity-Training',
 'saketvikram/cybersecurity-tools',
 'NatMk/Operational_Cybersecurity',
 'roklem314/cybersecuritybase-project',
 'cjspencer/UCB-Cybersecurity',
 'fedehsq/cybersecurity_timetable',
 'heycori/social-cybersecurity',
 'daylight-lab/cybersecurity-imagery',
 'MridulRastogi/Cybersecurity-Assignments',
 'GitJii/CyberSecurityFlaws',
 'jimTheSTEAMClown/Python-CyberSecurity-Code',
 'SergeyMyssak/cybersecurity-JavaFX',
 'pykira-cpu/AI_Cybersecurity_finalproject',
 'raj161100/Web-Application-Cybersecurity',
 'docfate111/general-cybersecurity-challenges',
 'Saket-Upadhyay/ns3-cybersecurity-simulations',
 'CJBOULDER/CyberSecurityBootcamp',
 'sprintup/CyberSecurityElkStack',
 'CDFriend/Cybersecurity-Ethical-Hacking-2018',
 'levitannin/AI-in-Cybersecurity',
 'cgajiwala/Database-project-for-Cybersecurity',
 'juhofriman/cybersecuritybase-project-2',
 'awharkrider/CPSC_3320_Cybersecurity_Lab',
 'laojala/cybersecuritybase-project-1',
 'NilesJiang/Cybersecurity-Risk-Management-Framework',
 'dylanp-git/AI-CyberSecurity',
 'mnsupreme/Python_For_Cybersecurity',
 'cgreen18/Cybersecurity-TinyOS-Encryption',
 'nathan-tw/Data-Science-for-Cybersecurity',
 'Amur-Cybersecurity/Amur-Cybersecurity.github.io',
 'n1n1n3sh4rk/osint-cybersecurity-books',
 'vvb231/ML-Cybersecurity-Project',
 'INSRapperswil/cybersecuritydays-2019-docker-lab',
 'ferryastika/datamining-for-cybersecurity-data',
 'Ramonywangziyao/CyberSecurityFinalProject',
 'hposton/python-for-cybersecurity',
 'MarkHyphen/CyberSecurity-Anomaly_Detection',
 'TarekHiemstra/cybersecuritybase-courseproject1',
 'froprintoai/ai4cybersecurity',
 'ensarseker1/Datasets-for-Cybersecurity',
 'Norah6/SDA_Cybersecurity_Bootcamp',
 'zuyar/CyberSecurityTermProject',
 'benchada/ML_CyberSecurity',
 'leowxx/ai-in-cybersecurity',
 'DavidBarbosadev/Flutter-CyberSecurity-Quizz',
 'PacktPublishing/Cybersecurity-Adversarial-Tradecraft',
 'GGTio/CyberSecuritySouthampton',
 'tugot17/ML-In-Cybersecurity-Paper',
 'allahuphallahupa/Cybersecurity.test.ru',
 'Crowgers/sponsor-gab-fer-cybersecurity',
 'fawad1997/CyberSecurityProjectMVC',
 'HaskellX/CyberSecurityTasks',
 'aman-gupta-1995/Robotics-CyberSecurity-',
 'tusharnankani/CyberSecurityWebsite',
 'gyanprakash0221/cybersecurity-and-pentesting-resources',
 'ekrismer/coursera-cybersecurity-capstone',
 'nickromandini/reinforcement-learning-cybersecurity',
 'beduExpert/Cybersecurity-Fundamentals-2020',
 'SteveDimitriadis/cyberSecurityTriviaGame',
 'cs-ahmed/hands-on_cybersecurity_material',
 'AbhishekBhattacharya/CyberSecurityMOOC-IITK',
 'Dwaragesh/CyberSecurity-Internship',
 'shahcker/ELK-Project-CyberSecurity',
 'YastaB/CyberSecurityHomework1',
 'titusnsharman/CyberSecurityProject1',
 '0xLockDown/CAT-CyberSecurity',
 'bestallouch/CyberSecurityProject',
 'N0vachr0n0/CyberSecurityNews_Alert',
 'hunwi/cybersecurity_Project-1',
 'gabrielcurrie/nist-cybersecurity-library',
 'werowe/cyberSecurityAnalytics',
 'SreenathYeragudi/CyberSecurityProjects',
 'Saket-Upadhyay/Nature-Inspired-Cybersecurity',
 'ajithkumar-natarajan/CodePath_CyberSecurity',
 'D3GKRyan/cyberSecurityPhishing',
 'Ingloryon/SHS_Cybersecurity_game',
 'viszsec/CyberSecurity-Playground',
 'Yuzi-Liu/CyberSecurity_Malware_Analysis',
 'lmfespinosa/Cybersecurity-POCs-Automation',
 'henchm4n/CyberSecurityBase2020',
 'WCY-dt/SEU-CyberSecurity-courses',
 'mburakergenc/Cybersecurity-Lab-Practices',
 'dinesh2043/CyberSecurityProject',
 'manju96mohan/Technergize-CyberSecurity-Team',
 'r3p3r/awesome-ml-for-cybersecurity',
 'Vedant-S/AI-chatbot-cybersecurity',
 'GanekarAmeyNarayan/Letsupgrade_CyberSecurity',
 'learning-cybersecurity-and-cryptography/learning-cybersecurity-and-cryptography-course',
 'AlexWangpsu/Bruce-Cybersecurity-Clssses-Search-Engine',
 'Charvik2020/CyberSecurity-University_of_Maryland',
 'nitinpathania007/Artificial-Intelligence-and-CyberSecurity',
 'PacktPublishing/Cybersecurity-Attacks---Red-Team-Strategies',
 'NIST-Cybersecurity-Framework-R1-1/NIST-Cybersecurity-Framework-R1-1.github.io',
 'Rodrig0Salinas/CyberSecurity',
 'acm-gmrit/cybersecurity',
 'Lilyshen1117/Cybersecurity',
 'RaphaelDiaz94/CyberSecurity',
 'hepitk/cybersecurity',
 'chovanecadam/cybersecurity',
 'jaimemarianoz/cybersecurity',
 'Fuork/CyberSecurity',
 'roytravel/Cybersecurity',
 'tr432/Cybersecurity',
 'Cyberattack535/Cybersecurity',
 'zeynobia/CyberSecurity',
 'jitendrajoshiinnopad/CyberSecurity',
 'jneville945/Cybersecurity',
 'theydvgaurav/Cybersecurity',
 'cybersecurity2020/cybersecurity2020.github.io',
 'tomkastan/CybersecurityBootcamp_Project1',
 'TheEvgenii/CybersecurityHW3',
 'alinapamfile/CybersecurityNews-Stage-1',
 'PADLab/CybersecurityCenterRepo',
 'AGENTGOOBER/CybersecurityWeek9',
 'maugarbru/cybersecurity2020-udem',
 '0xckylee/cybersecuritybase2021-mooc.fi',
 'jonOsm/CybersecurityBootcampScripts',
 'chygozprivaterepo/CybersecurityAE1',
 'spiritofecstasy/CybersecurityProject1',
 'ashemag/CybersecurityContextUSRussia',
 'jaymaliye/CybersecurityStockAnalysis',
 'EvanTimko/CybersecurityUniversitySpring2021',
 'TheEvgenii/CybersecurityHW4',
 'alinapamfile/CybersecurityNews-Stage-2',
 'TannerWalkerWhite/CybersecurityProject1',
 'nikomn/cybersecuritybase2021-project1',
 'Sarthak1911/CyberSecurity',
 'danielgriffin16/cybersecurity',
 'amirhilmi/Cybersecurity',
 'nemnous/CyberSecurity',
 'E-Coli-BW/CyberSecurity',
 'TheDerpyWombat/Cybersecurity',
 'dp540788912/CyberSecurity',
 'Jasm4228/CyberSecurity',
 'ckardaras/cybersecurity',
 'zacharyfrederick/cybersecurity',
 'BielxD/cybersecurity',
 'HarshVanasiwala-18/CyberSecurity',
 'YriyAntonov228/CyberSecurity',
 'debidattasuryaprakash/cybersecurity',
 'toussaintvla/Cybersecurity',
 'SIGCSE-BOF-Cybersecurity-Ed/SIGCSE_2021',
 'bywbilly/NUS_CybersecurityCamp',
 'naikshai2/CybersecurityAssignment9',
 'naikshai2/CybersecurityAssignment8',
 'al9897/cybersecuritySecuredNetwork',
 'nicomp42/CybersecurityGroupProject',
 'Sudiptobanerjee123/Java_Project_CybersecurityWorks',
 'pwnorbitals/CybersecurityReinforcementLearning',
 'asplitstone/CybersecurityProject2021',
 'ravitejapasumarthy/CyberSecurity',
 'jishanali2018/CyberSecurity',
 'Kareem13-sk/cybersecurity',
'CyberGruppo5/CyberSecurity',
 'jyotisharmak/cyberSecurity',
 'ashokreddy14/CyberSecurity',
 'prachikush/cybersecurity',
 'jarissaw/Cybersecurity',     
 'LucienCastle/CyberSecurity',
 'jrm1776/CyberSecurity',
 'heaps/cybersecurity',
 'c3divya/Cybersecurity',
 'ccesiguri/cybersecurity',
 'amark/gun',
 'comaeio/OPCDE',  
 'DerekBabb/CyberSecurity',
 'PacktPublishing/Machine-Learning-for-Cybersecurity-Cookbook',
 'EmpireCTF/empirectf',
 'scusec/Data-Mining-for-Cybersecurity',
 'cyber-prog0x/PoC-Bank',
 'noraj/rawsec-cybersecurity-inventory',
 'sgangol/CSCE-4550',
 'CyberGroup1/HashProject',
 'DanElias/Cybersecurity',
 'cyberlibrarian/cyberlibrarian.github.io',
 'MarwanAbdelatti/ICS_cybersec',
 'zerosmile/python-tools',
 'liamkar/cybersecurity1',
 'maayanco/SPL-Assignment1',
 'SKocur/Simple-Adware',
 'The20thDuck/nactf-2019',
 'Security-Prime/CS3501-Introduction-to-Cybersecurity-ICS',
 'classic89/UT-MCC-CYBER-PT-10-2019-U-C',
 'giovannyortegon/TheSecuritySentinel',
 'Jdelvillar103/COSC3371',
 'Hekez/usafe',
 'bhargavssbt38/Python_CyberSecurity',
 'sydneyvert/Fooling-our-Neural-Network',
 'learngrowlive/cs_basics',
 'marianomatelo/MLCybersecurity',
 'S4TURN0/Projects.py',
 'UTMUniverStuff/SI',
 'Lucianoga/CourseraOctoberCapstone',
 'utcoalition/Public-CTF-Writeups',
 'jonathan6661/P1sty',
 'spc16670/stegano',
 'jesseei/jesseei.github.io',
 'Patrowl/PatrowlHears',
 'marcoramilli/cybermomentum-web',
'tropicoo/zoneh',
'diogo-fernan/domfind',
'joaovitorbf/nwam',
'Frazew/Cybersecurity-HackademINT',]

        
headers = {"Authorization": f"token {github_token}", "User-Agent": github_username}

if headers["Authorization"] == "token " or headers["User-Agent"] == "":
    raise Exception(
        "You need to follow the instructions marked TODO in this script before trying to use it"
    )


def github_api_request(url: str) -> Union[List, Dict]:
    response = requests.get(url, headers=headers)
    response_data = response.json()
    if response.status_code != 200:
        raise Exception(
            f"Error response from github api! status code: {response.status_code}, "
            f"response: {json.dumps(response_data)}"
        )
    return response_data


def get_repo_language(repo: str) -> str:
    url = f"https://api.github.com/repos/{repo}"
    repo_info = github_api_request(url)
    if type(repo_info) is dict:
        repo_info = cast(Dict, repo_info)
        if "language" not in repo_info:
            raise Exception(
                "'language' key not round in response\n{}".format(json.dumps(repo_info))
            )
        return repo_info["language"]
    raise Exception(
        f"Expecting a dictionary response from {url}, instead got {json.dumps(repo_info)}"
    )


def get_repo_contents(repo: str) -> List[Dict[str, str]]:
    url = f"https://api.github.com/repos/{repo}/contents/"
    contents = github_api_request(url)
    if type(contents) is list:
        contents = cast(List, contents)
        return contents
    raise Exception(
        f"Expecting a list response from {url}, instead got {json.dumps(contents)}"
    )


def get_readme_download_url(files: List[Dict[str, str]]) -> str:
    """
    Takes in a response from the github api that lists the files in a repo and
    returns the url that can be used to download the repo's README file.
    """
    for file in files:
        if file["name"].lower().startswith("readme"):
            return file["download_url"]
    return ""


def process_repo(repo: str) -> Dict[str, str]:
    """
    Takes a repo name like "gocodeup/codeup-setup-script" and returns a
    dictionary with the language of the repo and the readme contents.
    """
    contents = get_repo_contents(repo)
    readme_download_url = get_readme_download_url(contents)
    if readme_download_url == "":
        readme_contents = ""
        print(repo)
    else:
        readme_contents = requests.get(readme_download_url).text
    return {
        "repo": repo,
        "language": get_repo_language(repo),
        "readme_contents": readme_contents,
    }


def scrape_github_data() -> List[Dict[str, str]]:
    """
    Loop through all of the repos and process them. Returns the processed data.
    """
    return [process_repo(repo) for repo in REPOS]


if __name__ == "__main__":
    data = scrape_github_data()
    json.dump(data, open("data.json", "w"), indent=1)